// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function factorial(x) {
  var match = x === 0;
  if (match) {
    return 1;
  } else {
    return Caml_int32.imul(x, factorial(x - 1 | 0));
  }
}

console.log(factorial(5));

exports.factorial = factorial;
/*  Not a pure module */
