// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function factorial(x) {
  var match = x === 0;
  if (match) {
    return 1;
  } else {
    return Caml_int32.imul(x, factorial(x - 1 | 0));
  }
}

console.log(factorial(5));

console.log(2);

var hola2 = /* record */[
  /* msg */"Hola, como estas?",
  /* lang */"Espanol"
];

console.log("Hola, que tal");

console.log("Hola, como estas?");

var a = /* Node */[
  5,
  /* Node */[
    4,
    /* Empty */0
  ]
];

function printSum(n) {
  if (n) {
    return n[0] + printSum(n[1]) | 0;
  } else {
    return 0;
  }
}

console.log(printSum(a));

var count = 1;

var hola = /* record */[
  /* msg */"Hola, que tal",
  /* lang */"Espanol"
];

exports.factorial = factorial;
exports.count = count;
exports.hola = hola;
exports.hola2 = hola2;
exports.a = a;
exports.printSum = printSum;
/*  Not a pure module */
