// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

var list = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* [] */0
    ]
  ]
];

var newList = List.map((function (x) {
        return x + 1 | 0;
      }), list);

List.iter((function (x) {
        console.log(x);
        return /* () */0;
      }), newList);

exports.list = list;
exports.newList = newList;
/* newList Not a pure module */
